### ISSUE TITLE
22_apply_network_plugin.yml let it wait a little longer

### ISSUE THREAD

**Issue by Bo-Zi** [kubealex/libvirt-k8s-provisioner#101]
I'd suggest setting `wait_timeout: 600`.
In my local deployment in takes around 3 minutes for all coredns pods to become ready,
but the default timeout for wait is 120 (2 minutes).
As a result -> 
```
<...> FAILED! => {"changed": false, "duration": 120, "method": "update", "msg": "\"Deployment\" \"coredns\": Timed out waiting on resource", <...>
```
I suggest:
```yaml
    - name: Wait for core-dns pods to be up and running
      kubernetes.core.k8s:
        state: present
        kind: Deployment
        name: coredns
...
        wait: true
        wait_timeout: 600
```
