### ISSUE TITLE
Loadbalancer firewall configuration does not persist through reboot

### ISSUE THREAD

**Issue by vmorris** [kubealex/libvirt-k8s-provisioner#9]
The configuration of the firewall in k8s-loadbalancer is not persisted through a reboot, I suspect this describes why:
https://access.redhat.com/discussions/1455033

Following a reboot I observe that `eth0` is no longer present in the `internal` zone:

```
internal
  target: default
  icmp-block-inversion: no
  interfaces: 
  sources: 
  services: dhcpv6-client http https mdns samba-client ssh
  ports: 6443/tcp
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
```

**Comment by vmorris** [comment]
After reboot, if I manually restart `firewalld` the interface is applied properly:

```
[root@k8s-loadbalancer ~]# firewall-cmd --info-zone=internal
internal
  target: default
  icmp-block-inversion: no
  interfaces: 
  sources: 
  services: dhcpv6-client http https mdns samba-client ssh
  ports: 6443/tcp
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
	
[root@k8s-loadbalancer ~]# systemctl restart firewalld
[root@k8s-loadbalancer ~]# firewall-cmd --info-zone=internal
internal (active)
  target: default
  icmp-block-inversion: no
  interfaces: eth0
  sources: 
  services: dhcpv6-client http https mdns samba-client ssh
  ports: 6443/tcp
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
	
```

It looks like there is more information here: 
https://bugzilla.redhat.com/show_bug.cgi?id=1112742

Unfortunately the workaround mentioned are not visible any longer on github. I wonder if this behavior is fixed in CentOS 8...
